import type { HudMessages } from './hudText.types';

/*
 * 英文包。两条和中文包不一样的规矩：
 *
 * 一、**战斗 HUD 那一段全大写，别处不是。** HUD 上都是一两个词的标签，全大写在像素字体里
 *     更齐整；而商店、战绩、结算里有整句的说明，全大写读起来像在喊。
 *
 * 二、**不要逐字翻。** 中文那边的说明是写给玩家看的短句，不是术语表；英文这边同样按英文的
 *     说法写。例如"够得比杂兵远一点"不是 "reach is farther than thug"，是 "Outreaches the
 *     rabble"。两边说的是同一件事，不是同一串词。
 */
export const HUD_TEXT_EN: HudMessages = {
  // ---------------------------------------------------------------- 战斗 HUD
  gameTitle: 'IronWall',
  playerLevel: 'Lv. {level}',
  health: 'HEALTH {value} / {maximum}',
  mana: 'MANA {value} / {maximum}',
  experience: 'EXPERIENCE {value} / {maximum}',
  experienceValue: 'XP {value} / {maximum}',
  wavePanel: 'MONSTER WAVE',
  waveTitle: 'WAVE {wave}',
  finalStandTitle: 'COUNTDOWN',
  nextWaveCountdown: 'NEXT WAVE IN {time}',
  waveProgress: '{completed} / {total} WAVES CLEARED',
  pauseHint: 'PRESS ESC TO PAUSE',
  language: 'LANGUAGE',
  sound: 'SOUND',
  music: 'MUSIC',
  on: 'ON',
  off: 'OFF',
  currencyInfo: 'CURRENCY',
  gold: 'GOLD',
  energy: 'SPIRIT STONES',
  gemProgress: 'BLUE GEM COLLECTION PROGRESS',
  activeSkills: 'ACTIVE SKILLS',
  activeSkillSlot: 'ACTIVE SKILL {key}',
  emptyActiveSkillSlot: 'ACTIVE SKILL {key}, EMPTY SLOT',
  itemQuickbar: 'ITEM QUICKBAR',
  itemSlot: 'ITEM SHORTCUT {key}',
  itemEffect: 'ITEM {key} EFFECT',
  cooldownPanel: 'SKILL AND EFFECT COOLDOWNS',
  currentItems: 'CARRYING',

  // ---------------------------------------------------------------- 通用按钮
  back: 'Back',
  confirm: 'Confirm',

  // ---------------------------------------------------------------- 技能
  skillSweep: 'SWEEP',
  skillSpin: 'SPIN',
  skillWave: 'WAVE',
  skillHeavenSplit: 'HEAVEN SPLIT',
  skillSkyArrow: 'SKY ARROW',
  skillLunge: 'LUNGE',
  skillAegis: 'GOLDEN BELL',
  skillDharma: 'DHARMA FORM',
  skillHeavenGuard: 'HEAVEN GUARD',
  skillSprint: 'SPRINT',
  skillIronBody: 'IRON BODY',
  skillBulwark: 'BULWARK',
  skillMend: 'MEND',
  skillBerserk: 'BERSERK',
  skillBloodthirst: 'BLOODTHIRST',

  skillSweepNote: 'A cone in front, resolved in one stroke',
  skillSpinNote: 'A full circle on the spot, for when you are surrounded',
  skillWaveNote: 'A wave rolls forward, killing everything it passes',
  skillHeavenSplitNote: 'A giant blade flies out along your heading, cutting through the crowd',
  skillSkyArrowNote: 'Shoots skyward, rains back down, spins where it lands',
  skillLungeNote: 'Charge forward; everything you hit dies',
  skillAegisNote: 'A shell that moves with you, flinging back whatever touches it',
  skillDharmaNote: 'Hold to keep it open, release to stop, drains mana',
  skillHeavenGuardNote: 'A rank of gilded heavy infantry drops in and ploughs a lane forward',
  skillSprintNote: 'Hold R or Shift to move faster, drains mana',
  skillIronBodyNote: 'Always on: the whole body glows and the rim light hardens',
  skillBulwarkNote: 'Always on: higher defense and maximum health',
  skillMendNote: 'Heals over ten seconds',
  skillBerserkNote: 'Eight seconds of much higher attack and attack rate, paid for with 10% health per second and weaker defense',
  skillBloodthirstNote: 'Always on: heal for a share of the damage you deal',

  skillKindAttack: 'Auto attack',
  skillKindProjectile: 'Projectile',
  skillKindGuard: 'Guard',
  skillKindActive: 'Active',

  // ---------------------------------------------------------------- 商店
  shopTitle: 'Shop',
  shelfRoots: 'Foundations',
  shelfRootsNote: 'Permanent stats, shared by every hero',
  shelfMastery: 'Mastery',
  shelfMasteryNote: 'The skill already starts at this level when you get it',
  shelfSupply: 'Supplies',
  shelfSupplyNote: 'Never drops in battle. One purchase lasts one run, delivered to your quickbar',
  rootOwnedBonus: 'Now +{value}%',
  rootPerRankBonus: '+{value}% per rank',
  masteryStartLevel: 'Starts at level {level}',
  supplyStock: 'Stock {owned} / {max}',
  supplyFull: 'Stocked up',
  rankFull: 'Maxed',

  rootMaxHp: 'Health',
  rootAttack: 'Attack',
  rootDefense: 'Defense',
  rootMoveSpeed: 'Speed',
  rootAttackSpeed: 'Agility',
  rootAttackRange: 'Range',

  // ---------------------------------------------------------------- 丹与符
  pickupHealName: 'Healing Pill',
  pickupHealNote: 'Restores 30% health at once',
  pickupManaName: 'Mana Pill',
  pickupManaNote: 'Restores 40% mana at once',
  pickupRegenName: 'Lifespring Pill',
  pickupRegenNote: '4.5% health per second for 8 seconds',
  pickupFocusName: 'Focus Pill',
  pickupFocusNote: '6% mana per second for 8 seconds',
  pickupHasteName: 'Swiftstep Charm',
  pickupHasteNote: '+18% move speed and +15% attack for 12 seconds',
  pickupWardName: 'Bulwark Charm',
  pickupWardNote: '+25% maximum health and mana for 15 seconds, filled the moment it lands',
  pickupRageName: 'Fury Charm',
  pickupRageNote: '+40% attack and −25% defense for 15 seconds',
  pickupGaleName: 'Gale Charm',
  pickupGaleNote: '+35% move speed and +20% attack rate for 15 seconds',
  pickupGoldenName: 'Golden Body Charm',
  pickupGoldenNote: 'Maximum health ×6 for 10 seconds, filled the moment it lands',
  pickupFortuneName: 'Fortune Charm',
  pickupFortuneNote: 'Doubles gold drops for the rest of the run',

  // ---------------------------------------------------------------- 清档
  resetTitle: 'Reset',
  resetConfirm: 'Sure?',
  resetDone: 'Wiped',

  // ---------------------------------------------------------------- 战绩
  historyTitle: 'Records',
  historyRuns: '{runs} runs',
  historyNotPlayed: 'Never played',
  historyTotal: 'Lifetime',
  historyWinRate: 'Win rate',
  historyWinRateValue: '{percent}% ({wins} won / {runs} runs)',
  historyKills: 'Total kills',
  historyBosses: 'Bosses slain',
  historyDamageTaken: 'Damage taken',
  historyTotalTime: 'Total time',
  historyBestWave: 'Best wave',
  historyLastRun: 'Last run',
  historyNeverPlayed: 'No runs with this hero yet',
  historyResult: 'Result',
  historyWon: 'Cleared',
  historyLost: 'Defeated',
  historyKillsOne: 'Kills',
  historyTimeOne: 'Time',
  historyWave: 'Wave',
  agoJustNow: 'Just now',
  agoMinutes: '{count} min ago',
  agoHours: '{count} h ago',
  agoDays: '{count} d ago',

  // ---------------------------------------------------------------- 结算 / 暂停
  summaryResume: 'Resume',
  summaryEnd: 'End run',
  summaryEndConfirm: 'Confirm end',
  summaryWonTitle: 'Every Boss Down',
  summaryDefeatedTitle: 'Bosses Still Standing',
  summaryOverTitle: 'Run Over',
  summaryPausedTitle: 'Paused',
  summaryVerdictWon: 'CLEARED',
  summaryVerdictLost: 'DEFEATED',
  summaryWaves: '{count} waves',
  summaryNoteWon: 'Reached level {level}. +{coins} gold banked; spirit stones only count within a run.',
  summaryNoteDefeated: 'That is the end of this run. Confirm to return to hero select, where you can take another hero or another map.',
  summaryNoteEnded: 'You ended this run yourself. Confirm to return to hero select.',
  summaryNotePaused: 'Resuming drops you back into the same moment, with everything still on the field. Experience and gold are settled when the run ends.',
  statKills: 'Kills',
  statDeaths: 'Deaths',
  statDamageTaken: 'Damage taken',
  statTime: 'Time',
  statWave: 'Wave',
  statCleared: 'Cleared',
  statLoot: 'Pickups',
  statExp: 'XP',
  statLevel: 'Level',
  statGold: 'Gold',
  statGems: 'Spirit stones',

  // ---------------------------------------------------------------- 备战界面
  setupStart: 'Start',
  setupEntering: 'Entering…',
  setupLead: 'Choose your hero and your battlefield',
  setupGrowth: 'Growth',
  setupEnvironment: 'Battlefield',
  setupTerrain: 'Terrain',
  setupSight: 'Sight',
  setupWeather: 'Weather',
  setupObjective: 'Objective',
  setupFoes: 'Who you will face',
  setupBossTag: '{name} · Boss',
  setupSpawn: 'Spawn',
  setupCamp: 'Camp',
  setupMapHint: 'Drag with left mouse · scroll to zoom',
  setupEnteringMap: 'Entering · {map}',
  setupEnteringHero: 'Hero: {hero}',
  setupPreparing: 'Preparing the battlefield…',
  statHp: 'Health',
  statAttack: 'Attack',
  statDefense: 'Defense',
  statSpeed: 'Speed',
  statAgility: 'Agility',
  statCrit: 'Crit',
  statRange: 'Range',
  statPickup: 'Pickup',
  archetypeOffense: 'Offense',
  archetypeDefense: 'Defense',
  archetypeSpeed: 'Speed',
  archetypeBalanced: 'Balanced',
  weatherClear: 'Clear',
  weatherRain: 'Rain',
  weatherSnow: 'Snow',

  // ---------------------------------------------------------------- 三选一属性牌
  cardPicker: 'Level-up cards',
  cardAttack: 'Attack',
  cardAttackDetail: 'All damage +{value}%',
  cardAttackSpeed: 'Attack rate',
  cardAttackSpeedDetail: 'Every attack rate +{value}%',
  cardAttackRange: 'Attack range',
  cardAttackRangeDetail: 'Every hit area +{value}%',
  cardPickupRange: 'Pickup range',
  cardPickupRangeDetail: 'Stones and gold are pulled in from +{value}% farther',
  cardDefense: 'Defense',
  cardDefenseDetail: 'Take less damage (defense +{value}%)',
  cardMoveSpeed: 'Move speed',
  cardMoveSpeedDetail: 'Walking and sprinting +{value}%',
  cardMaxHp: 'Max health',
  cardMaxHpDetail: 'Maximum health +{value}%',
  cardMpRegen: 'Mana regen',
  cardMpRegenDetail: 'Mana per second +{value}%',
  cardLevelUp: 'Level +1',
  cardObtain: 'Unlocks a {kind} skill',
  cardSkillUpgrade: 'Level {from} → {to} (damage +{damage}%, range +{reach}%)',

  // ---------------------------------------------------------------- 角色
  heroWarlordName: 'Twin-Hammer Warlord',
  heroWarlordTagline: 'Sweeps at close range',
  heroWarlordBlurb: 'Two heavy hammers clear the ground in front of him; even standing inside the crowd he can shove it open.',
  heroKnightName: 'Knight',
  heroKnightTagline: 'Shield through the line',
  heroKnightBlurb: 'Sword in one hand, shield in the other. Spin clears whoever is on top of you, then you push into the next knot behind the shield.',
  heroBladeName: 'Caped Swordsman',
  heroBladeTagline: 'Cuts from a distance',
  heroBladeBlurb: 'The longest reach of the four: send a wave out, everything it passes falls, and you never have to squeeze into the crowd.',
  heroLancerName: 'Cavalry General',
  heroLancerTagline: 'Lance from horseback',
  heroLancerBlurb: 'The only mounted one: taller than anyone from the saddle, with the longest reach, fighting by riding in and riding out again.',

  // ---------------------------------------------------------------- 敌人
  unitThugName: 'Rabble',
  unitThugNote: 'The most numerous; cuts you up close',
  unitPeasantName: 'Peasant',
  unitPeasantNote: 'The ones on foot, there to fill out the numbers',
  unitSpearmanName: 'Spearman',
  unitSpearmanNote: 'Outreaches the rabble by a step',
  unitShieldmanName: 'Shieldman',
  unitShieldmanNote: 'Hard from the front; go around',
  unitBulwarkName: 'Heavy Infantry',
  unitBulwarkNote: 'Tower shield and a levelled spear; a frontal charge gets nowhere',
  unitArcherName: 'Archer',
  unitArcherNote: 'Shoots from the back',
  unitHalberdierName: 'Halberdier',
  unitHalberdierNote: 'Brings it down overhead, further than a blade',
  unitCavalryName: 'Cavalry',
  unitCavalryNote: 'Only shows up later; taller and faster than anyone',
  unitLancerName: 'Lancer',
  unitLancerNote: 'Barded horse, the longest reach on the field',
  unitHorseArcherName: 'Horse Archer',
  unitHorseArcherNote: 'Shoots on the move; you will not catch it',
  unitEliteName: 'Elite Commander',
  unitEliteNote: 'Tower shield and heavy plate, hard as a wall',
  unitKnightBossName: 'Knight Commander',
  unitKnightBossNote: 'Visored helm and round shield: faster than the elite, and softer',

  // ---------------------------------------------------------------- 地图
  mapProvingName: 'Proving Grounds',
  mapProvingTag: 'Woodland',
  mapProvingBlurb: 'A flat clearing walled in on all four sides by trees, with a few ponds and worn dirt paths through the middle.',
  mapProvingTerrain: 'Mostly grass, a few thickets and ponds, a dirt road across the centre',
  mapProvingWeather: 'Clear; rain and snow can be switched on mid-run',
  mapProvingSight: 'Open all round; only thickets and the tree wall block your view',
  mapProvingObjective: 'Hold off the waves that keep coming.',
  mapProvingBossName: 'Elite Commander',
  mapPassName: 'Blackstone Pass',
  mapPassTag: 'Canyon',
  mapPassBlurb: 'A narrow north-south valley between two walls, pinched thinnest in the middle by woods on both sides, with one dirt road running end to end.',
  mapPassTerrain: 'One road down the length, dense woods pressed to its edges, no water',
  mapPassWeather: 'Overcast, high wind',
  mapPassSight: 'The worst of the four: the woods at the midpoint kill your side vision',
  mapPassObjective: 'Hold six waves inside the narrow valley.',
  mapPassBossName: 'Pass Warden',
  mapSteppeName: 'Red Sand Steppe',
  mapSteppeTag: 'Steppe',
  mapSteppeBlurb: 'A wide run of sandy grass; the ring of trees at the edge is too thin to hide anything, with bare sand patches scattered about.',
  mapSteppeTerrain: 'Wide open grass, five sand patches, only a thin treeline at the rim',
  mapSteppeWeather: 'Clear, hard sun',
  mapSteppeSight: 'The best of the four: you can see the far treeline from where you stand',
  mapSteppeObjective: 'Survive six waves of cavalry charges in the open.',
  mapSteppeBossName: 'Steppe Chieftain',
  mapSnowName: 'Whiteridge Snowfield',
  mapSnowTag: 'Snowfield',
  mapSnowBlurb: 'A gentle snow-covered slope around a frozen lake, with three stands of fir reaching in from the edges — they stop arrows.',
  mapSnowTerrain: 'A frozen lake at the centre, three stands of fir reaching in, snowed-over grass elsewhere',
  mapSnowWeather: 'Snow, falling from the start',
  mapSnowSight: 'Middling: the lake hides nothing, the woods hide everything',
  mapSnowObjective: 'Survive six waves under the arrows.',
  mapSnowBossName: 'Snowfield Headhunter',
  mapBossPending: 'not in the wave table yet',

  // ---------------------------------------------------------------- 加载
  loadingTitle: 'Loading game assets…',
  bootRenderer: 'Starting the renderer',
  bootTerrain: 'Generating terrain',
  bootBake: 'Baking the ground',
  bootItems: 'Loading item art',
  bootAudio: 'Loading sound effects',
  bootField: 'Setting up the battlefield',
};
