import type { HudMessages } from './hudText.types';

export const HUD_TEXT_ZH_CN: HudMessages = {
  // ---------------------------------------------------------------- 战斗 HUD
  gameTitle: '铁壁',
  playerLevel: '等级 {level}',
  health: '生命值 {value} / {maximum}',
  mana: '法力值 {value} / {maximum}',
  experience: '经验值 {value} / {maximum}',
  experienceValue: '经验 {value} / {maximum}',
  wavePanel: '怪物波次',
  waveTitle: '第 {wave} 波',
  finalStandTitle: '倒 计 时',
  nextWaveCountdown: '下一波倒计时 {time}',
  waveProgress: '已打完 {completed} / {total} 波',
  pauseHint: '按 ESC 暂停',
  language: '语言',
  sound: '音效',
  music: '音乐',
  on: '开',
  off: '关',
  currencyInfo: '货币信息',
  gold: '金币',
  energy: '灵石',
  gemProgress: '蓝色宝石收集进度',
  activeSkills: '主动技能栏',
  activeSkillSlot: '主动技能 {key}',
  emptyActiveSkillSlot: '主动技能 {key}，空槽位',
  itemQuickbar: '物品快捷栏',
  itemSlot: '物品快捷键 {key}',
  itemEffect: '物品 {key} 效果',
  cooldownPanel: '技能与药效冷却',
  currentItems: '当前物品',

  // ---------------------------------------------------------------- 通用按钮
  back: '返回',
  confirm: '确认',

  // ---------------------------------------------------------------- 技能
  skillSweep: '横扫',
  skillSpin: '回旋',
  skillWave: '破空',
  skillHeavenSplit: '开天',
  skillSkyArrow: '穿云箭',
  skillLunge: '突进',
  skillAegis: '金钟罩',
  skillDharma: '天地法相',
  skillHeavenGuard: '神兵天降',
  skillSprint: '疾走',
  skillIronBody: '铁布衫',
  skillBulwark: '磐石',
  skillMend: '回春',
  skillBerserk: '狂暴',
  skillBloodthirst: '饮血',

  skillSweepNote: '前方扇形，一次算清',
  skillSpinNote: '原地整圈，被围住时用',
  skillWaveNote: '波向前飞，路过就死',
  skillHeavenSplitNote: '巨剑沿行走朝向飞出，剑体横扫敌群',
  skillSkyArrowNote: '冲天后随机落下，落地回旋',
  skillLungeNote: '向前冲，撞到的全死',
  skillAegisNote: '罩子跟着人走，碰到就飞',
  skillDharmaNote: '按住持续展开，松手立停，持续耗蓝',
  skillHeavenGuardNote: '一排金甲重兵砸下来，端矛朝前推平一条路',
  skillSprintNote: '按住 R 或 Shift 加速移动，持续耗蓝',
  skillIronBodyNote: '永久生效，通体呼吸提亮并强化轮廓光',
  skillBulwarkNote: '永久生效，防御与生命上限提高',
  skillMendNote: '十秒内持续回血',
  skillBerserkNote: '八秒内攻击与出手频率大涨，代价是每秒掉一成血、防御变弱',
  skillBloodthirstNote: '永久生效，造成伤害按比例回血',

  skillKindAttack: '自动攻击技',
  skillKindProjectile: '发射',
  skillKindGuard: '护身',
  skillKindActive: '主动技',

  // ---------------------------------------------------------------- 商店
  shopTitle: '商店',
  shelfRoots: '根基',
  shelfRootsNote: '永久属性，所有角色共享',
  shelfMastery: '师承',
  shelfMasteryNote: '这一招到手时就已经是这一级',
  shelfSupply: '补给',
  shelfSupplyNote: '游戏里打不出来，买一次用一局，进图发到快捷栏',
  rootOwnedBonus: '已 +{value}%',
  rootPerRankBonus: '每级 +{value}%',
  masteryStartLevel: '起始 {level} 级',
  supplyStock: '屯 {owned} / {max}',
  supplyFull: '已屯满',
  rankFull: '已满级',

  rootMaxHp: '生命',
  rootAttack: '进攻',
  rootDefense: '防御',
  rootMoveSpeed: '速度',
  rootAttackSpeed: '敏捷',
  rootAttackRange: '范围',

  // ---------------------------------------------------------------- 丹与符
  pickupHealName: '回血丹',
  pickupHealNote: '立刻回三成生命',
  pickupManaName: '回蓝丹',
  pickupManaNote: '立刻回四成法力',
  pickupRegenName: '续命丹',
  pickupRegenNote: '8 秒内每秒回 4.5% 生命',
  pickupFocusName: '凝神丹',
  pickupFocusNote: '8 秒内每秒回 6% 法力',
  pickupHasteName: '疾行符',
  pickupHasteNote: '12 秒内移动速度 +18%，攻击力 +15%',
  pickupWardName: '坚壁符',
  pickupWardNote: '15 秒内生命与法力上限 +25%，涨出来的当场补满',
  pickupRageName: '狂暴符',
  pickupRageNote: '15 秒内攻击力 +40%，防御 −25%',
  pickupGaleName: '疾风符',
  pickupGaleNote: '15 秒内移动速度 +35%，出手频率 +20%',
  pickupGoldenName: '金身符',
  pickupGoldenNote: '10 秒内生命上限 ×6，涨出来的当场补满',
  pickupFortuneName: '聚宝符',
  pickupFortuneNote: '本局金币掉落翻倍',

  // ---------------------------------------------------------------- 战绩
  historyTitle: '战绩',
  historyRuns: '{runs} 局',
  historyNotPlayed: '未出战',
  historyTotal: '累计',
  historyWinRate: '胜率',
  historyWinRateValue: '{percent}%（{wins} 胜 / {runs} 局）',
  historyKills: '总击杀',
  historyBosses: '斩首领',
  historyDamageTaken: '承受伤害',
  historyTotalTime: '总时长',
  historyBestWave: '最远波次',
  historyLastRun: '最近一场',
  historyNeverPlayed: '还没有用这个角色打过',
  historyResult: '结果',
  historyWon: '通关',
  historyLost: '战败',
  historyKillsOne: '击杀',
  historyTimeOne: '用时',
  historyWave: '波次',
  agoJustNow: '刚刚',
  agoMinutes: '{count} 分钟前',
  agoHours: '{count} 小时前',
  agoDays: '{count} 天前',

  // ---------------------------------------------------------------- 结算 / 暂停
  summaryResume: '继续游戏',
  summaryEnd: '结束游戏',
  summaryEndConfirm: '确认结束',
  summaryWonTitle: '全数斩首',
  summaryDefeatedTitle: '首领未除',
  summaryOverTitle: '本局结束',
  summaryPausedTitle: '游戏暂停',
  summaryVerdictWon: '通 关',
  summaryVerdictLost: '战 败',
  summaryWaves: '{count} 波',
  summaryNoteWon: '升到了 {level} 级。金币 +{coins} 已存入，灵石只在本局有效。',
  summaryNoteDefeated: '这一局到此为止。确认之后回到选人画面，可以换个角色或者换张地图再来。',
  summaryNoteEnded: '这一局由你主动结束。确认之后回到选人画面。',
  summaryNotePaused: '继续游戏会回到刚才那一刻，场上的人和捡到的东西都还在。经验和金币要打完这一局才结算。',
  statKills: '击杀',
  statDeaths: '阵亡',
  statDamageTaken: '承受伤害',
  statTime: '用时',
  statWave: '波次',
  statCleared: '已清',
  statLoot: '收集物',
  statExp: '经验',
  statLevel: '等级',
  statGold: '金币',
  statGems: '灵石',

  // ---------------------------------------------------------------- 备战界面
  setupStart: '开始游戏',
  setupEntering: '正在进入…',
  setupLead: '选择出战角色与地图',
  setupGrowth: '成长',
  setupEnvironment: '战场环境',
  setupTerrain: '地形',
  setupSight: '视野',
  setupWeather: '天候',
  setupObjective: '本局目标',
  setupFoes: '出兵人物',
  setupBossTag: '{name} · 首领',
  setupSpawn: '进入位置',
  setupCamp: '营地',
  setupMapHint: '左键拖动 · 滚轮缩放',
  setupEnteringMap: '正在进入 · {map}',
  setupEnteringHero: '出战角色：{hero}',
  setupPreparing: '准备战场…',
  statHp: '生命',
  statAttack: '进攻',
  statDefense: '防御',
  statSpeed: '速度',
  statAgility: '敏捷',
  statCrit: '暴击',
  statRange: '范围',
  statPickup: '拾取',
  archetypeOffense: '进攻型',
  archetypeDefense: '防御型',
  archetypeSpeed: '速度型',
  archetypeBalanced: '均衡型',
  weatherClear: '晴',
  weatherRain: '雨',
  weatherSnow: '雪',

  // ---------------------------------------------------------------- 三选一属性牌
  cardPicker: '升级卡牌',
  cardAttack: '攻击力',
  cardAttackDetail: '所有伤害 +{value}%',
  cardAttackSpeed: '攻击频率',
  cardAttackSpeedDetail: '所有出手频率 +{value}%',
  cardAttackRange: '攻击范围',
  cardAttackRangeDetail: '所有判定范围 +{value}%',
  cardPickupRange: '拾取范围',
  cardPickupRangeDetail: '灵石与金币吸附范围 +{value}%',
  cardDefense: '防御',
  cardDefenseDetail: '受到的伤害减少（防御 +{value}%）',
  cardMoveSpeed: '移动速度',
  cardMoveSpeedDetail: '走和跑都 +{value}%',
  cardMaxHp: '生命上限',
  cardMaxHpDetail: '生命上限 +{value}%',
  cardMpRegen: '法力回复',
  cardMpRegenDetail: '每秒回蓝 +{value}%',
  cardLevelUp: '等级 +1',
  cardObtain: '获得【{kind}】',
  cardSkillUpgrade: '{from} 级 → {to} 级（伤害 +{damage}%，范围 +{reach}%）',

  // ---------------------------------------------------------------- 角色
  heroWarlordName: '双锤武将',
  heroWarlordTagline: '近身横扫',
  heroWarlordBlurb: '两柄重锤扫开身前一片，站在人堆中间也能把人堆推开。',
  heroKnightName: '骑士',
  heroKnightTagline: '持盾破阵',
  heroKnightBlurb: '一手剑一手盾，靠回旋清开贴身的人，再顶着盾冲进下一堆。',
  heroBladeName: '披风剑士',
  heroBladeTagline: '远程破空',
  heroBladeBlurb: '出手最远的一个：一道破空推出去，路过的都倒，自己不用挤进人堆。',
  heroLancerName: '骠骑将军',
  heroLancerTagline: '马上长枪',
  heroLancerBlurb: '唯一骑马的一个：坐在鞍上比谁都高，枪够得也最远，靠冲进去再冲出来打。',

  // ---------------------------------------------------------------- 敌人
  unitThugName: '杂兵',
  unitThugNote: '数量最多，贴身砍',
  unitPeasantName: '流民',
  unitPeasantNote: '徒步的那一部分，填数量',
  unitSpearmanName: '长枪兵',
  unitSpearmanNote: '够得比杂兵远一点',
  unitShieldmanName: '持盾兵',
  unitShieldmanNote: '正面难打，绕后',
  unitBulwarkName: '重甲兵',
  unitBulwarkNote: '塔盾加一杆平举的长矛，正面撞不动',
  unitArcherName: '弓手',
  unitArcherNote: '站远处放箭',
  unitHalberdierName: '戟兵',
  unitHalberdierNote: '举过头顶砸下来，够得比刀远',
  unitCavalryName: '骑兵',
  unitCavalryNote: '后段才来，比谁都高、比谁都快',
  unitLancerName: '枪骑兵',
  unitLancerNote: '披着马衣，够得最远',
  unitHorseArcherName: '骑射',
  unitHorseArcherNote: '边跑边放箭，追不上',
  unitEliteName: '精锐统领',
  unitEliteNote: '塔盾与重甲，硬得像一堵墙',
  unitKnightBossName: '骑士统领',
  unitKnightBossNote: '面甲与圆盾，比精锐快，也比精锐软',

  // ---------------------------------------------------------------- 地图
  mapProvingName: '演武荒原',
  mapProvingTag: '林地',
  mapProvingBlurb: '四面合围的一块平地，边上是围死的树墙，中间散着几处水塘和踩出来的土路。',
  mapProvingTerrain: '草地为主，几片林地和水塘，土路穿过中央',
  mapProvingWeather: '晴，局内可切雨雪',
  mapProvingSight: '全场开阔，只有林地和树墙挡视线',
  mapProvingObjective: '抵御不断来袭的敌人。',
  mapProvingBossName: '精锐统领',
  mapPassName: '黑石隘口',
  mapPassTag: '峡谷',
  mapPassBlurb: '两壁夹着的一条南北向窄谷，中段被两侧的林子掐得最细，一条土路从头贯到尾。',
  mapPassTerrain: '一条纵贯的土路，两侧密林压到路边，没有水',
  mapPassWeather: '阴，风大',
  mapPassSight: '最差的一张：中段两侧的林子挡死侧向视野',
  mapPassObjective: '在窄谷里顶住六波推进。',
  mapPassBossName: '隘口守将',
  mapSteppeName: '赤沙荒原',
  mapSteppeTag: '荒原',
  mapSteppeBlurb: '一整片跑得开的沙草地，边上那圈林子薄得几乎挡不住视线，地上散着几块踩秃的沙土。',
  mapSteppeTerrain: '大片开阔草地，五处沙土，边缘只有一层薄林',
  mapSteppeWeather: '晴，日头很足',
  mapSteppeSight: '最好的一张：一眼能看到对面的林线',
  mapSteppeObjective: '在开阔地上撑过六波骑兵冲锋。',
  mapSteppeBossName: '荒原头人',
  mapSnowName: '白岭雪原',
  mapSnowTag: '雪原',
  mapSnowBlurb: '一片积着雪的缓坡，中间是冻住的大湖，三片杉林从边上探进来，能挡箭。',
  mapSnowTerrain: '中央一片冻湖，三片探入场内的林子，其余是积雪的草地',
  mapSnowWeather: '雪，默认就在下',
  mapSnowSight: '中等：湖面一览无余，林子里看不清',
  mapSnowObjective: '在箭雨底下撑过六波。',
  mapSnowBossName: '雪原猎首',
  mapBossPending: '尚未出现在波次里',

  // ---------------------------------------------------------------- 加载
  loadingTitle: '正在加载游戏资源…',
  bootRenderer: '启动渲染器',
  bootTerrain: '生成地形',
  bootBake: '烘制地面',
  bootItems: '加载物品贴图',
  bootAudio: '加载音效',
  bootField: '布置战场',
};
